import image from '../profile.jfif';

const employees = [
  {
    image,
    name: "Darlene Robertson",
    id: "345321231",
    dept: "Design",
    role: "UI/UX Designer",
    designation: "Lead Designer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:27 AM"
  },
  {
    image,
    name: "Floyd Miles",
    id: "987890345",
    dept: "Development",
    role: "PHP Developer",
    designation: "Backend Developer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:45 AM"
  },
  {
    image,
    name: "Cody Fisher",
    id: "453367122",
    dept: "Sales",
    role: "Sales Manager",
    designation: "Regional Manager",
    type: "Office",
    status: "Permanent",
    checkInTime: "10:10 AM"
  },
  {
    image,
    name: "Dianne Russell",
    id: "345321231",
    dept: "Sales",
    role: "BDM",
    designation: "Business Development Manager",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:30 AM"
  },
  {
    image,
    name: "Savannah Nguyen",
    id: "453677881",
    dept: "Design",
    role: "Design Lead",
    designation: "Senior Designer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:12 AM"
  },
  {
    image,
    name: "Jacob Jones",
    id: "009918765",
    dept: "Development",
    role: "Python Developer",
    designation: "Backend Developer",
    type: "Remote",
    status: "Permanent",
    checkInTime: "10:24 AM"
  },
  {
    image,
    name: "Marvin McKinney",
    id: "238870122",
    dept: "Development",
    role: "Sr. UI Developer",
    designation: "Frontend Developer",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:29 AM"
  },
  {
    image,
    name: "Brooklyn Simmons",
    id: "124355111",
    dept: "PM",
    role: "Project Manager",
    designation: "PMO Head",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:15 AM"
  },
  {
    image,
    name: "Kristin Watson",
    id: "435540099",
    dept: "HR",
    role: "HR Executive",
    designation: "Recruitment Lead",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:20 AM"
  },
  {
    image,
    name: "Kathryn Murphy",
    id: "009812890",
    dept: "Development",
    role: "React JS Developer",
    designation: "Frontend Engineer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:10 AM"
  },
  {
    image,
    name: "Arlene McCoy",
    id: "671190345",
    dept: "Development",
    role: "Node JS",
    designation: "Backend Engineer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:22 AM"
  },
  {
    image,
    name: "Devon Lane",
    id: "091233412",
    dept: "BA",
    role: "Business Analyst",
    designation: "Sr. Analyst",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:32 AM"
  },
  {
    image,
    name: "Darlene Robertson",
    id: "345321231",
    dept: "Design",
    role: "UI/UX Designer",
    designation: "Lead Designer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:27 AM"
  },
  {
    image,
    name: "Floyd Miles",
    id: "987890345",
    dept: "Development",
    role: "PHP Developer",
    designation: "Backend Developer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:45 AM"
  },
  {
    image,
    name: "Cody Fisher",
    id: "453367122",
    dept: "Sales",
    role: "Sales Manager",
    designation: "Regional Manager",
    type: "Office",
    status: "Permanent",
    checkInTime: "10:10 AM"
  },
  {
    image,
    name: "Dianne Russell",
    id: "345321231",
    dept: "Sales",
    role: "BDM",
    designation: "Business Development Manager",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:30 AM"
  },
  {
    image,
    name: "Savannah Nguyen",
    id: "453677881",
    dept: "Design",
    role: "Design Lead",
    designation: "Senior Designer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:12 AM"
  },
  {
    image,
    name: "Jacob Jones",
    id: "009918765",
    dept: "Development",
    role: "Python Developer",
    designation: "Backend Developer",
    type: "Remote",
    status: "Permanent",
    checkInTime: "10:24 AM"
  },
  {
    image,
    name: "Marvin McKinney",
    id: "238870122",
    dept: "Development",
    role: "Sr. UI Developer",
    designation: "Frontend Developer",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:29 AM"
  },
  {
    image,
    name: "Brooklyn Simmons",
    id: "124355111",
    dept: "PM",
    role: "Project Manager",
    designation: "PMO Head",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:15 AM"
  },
  {
    image,
    name: "Kristin Watson",
    id: "435540099",
    dept: "HR",
    role: "HR Executive",
    designation: "Recruitment Lead",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:20 AM"
  },
  {
    image,
    name: "Kathryn Murphy",
    id: "009812890",
    dept: "Development",
    role: "React JS Developer",
    designation: "Frontend Engineer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:10 AM"
  },
  {
    image,
    name: "Arlene McCoy",
    id: "671190345",
    dept: "Development",
    role: "Node JS",
    designation: "Backend Engineer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:22 AM"
  },
  {
    image,
    name: "Devon Lane",
    id: "091233412",
    dept: "BA",
    role: "Business Analyst",
    designation: "Sr. Analyst",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:32 AM"
  },
  {
    image,
    name: "Darlene Robertson",
    id: "345321231",
    dept: "Design",
    role: "UI/UX Designer",
    designation: "Lead Designer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:27 AM"
  },
  {
    image,
    name: "Floyd Miles",
    id: "987890345",
    dept: "Development",
    role: "PHP Developer",
    designation: "Backend Developer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:45 AM"
  },
  {
    image,
    name: "Cody Fisher",
    id: "453367122",
    dept: "Sales",
    role: "Sales Manager",
    designation: "Regional Manager",
    type: "Office",
    status: "Permanent",
    checkInTime: "10:10 AM"
  },
  {
    image,
    name: "Dianne Russell",
    id: "345321231",
    dept: "Sales",
    role: "BDM",
    designation: "Business Development Manager",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:30 AM"
  },
  {
    image,
    name: "Savannah Nguyen",
    id: "453677881",
    dept: "Design",
    role: "Design Lead",
    designation: "Senior Designer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:12 AM"
  },
  {
    image,
    name: "Jacob Jones",
    id: "009918765",
    dept: "Development",
    role: "Python Developer",
    designation: "Backend Developer",
    type: "Remote",
    status: "Permanent",
    checkInTime: "10:24 AM"
  },
  {
    image,
    name: "Marvin McKinney",
    id: "238870122",
    dept: "Development",
    role: "Sr. UI Developer",
    designation: "Frontend Developer",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:29 AM"
  },
  {
    image,
    name: "Brooklyn Simmons",
    id: "124355111",
    dept: "PM",
    role: "Project Manager",
    designation: "PMO Head",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:15 AM"
  },
  {
    image,
    name: "Kristin Watson",
    id: "435540099",
    dept: "HR",
    role: "HR Executive",
    designation: "Recruitment Lead",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:20 AM"
  },
  {
    image,
    name: "Kathryn Murphy",
    id: "009812890",
    dept: "Development",
    role: "React JS Developer",
    designation: "Frontend Engineer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:10 AM"
  },
  {
    image,
    name: "Arlene McCoy",
    id: "671190345",
    dept: "Development",
    role: "Node JS",
    designation: "Backend Engineer",
    type: "Office",
    status: "Permanent",
    checkInTime: "09:22 AM"
  },
  {
    image,
    name: "Devon Lane",
    id: "091233412",
    dept: "BA",
    role: "Business Analyst",
    designation: "Sr. Analyst",
    type: "Remote",
    status: "Permanent",
    checkInTime: "09:32 AM"
  },
  // Copy and repeat as needed
];

export default employees;
